name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh

      - name: Deploy code
        run: |
          ssh-keyscan 3.145.39.92 >> ~/.ssh/known_hosts
          scp -r -i ~/.ssh/id_rsa ./apps/cvforge-fe <ec2-user>@3.145.39.92:apps/cvforge-fe
